# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: CodeQuality PMD Tests
      run: mvn install
    - uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: CodeCoverage Archive
        path: /home/runner/work/pipeline-hello-world/pipeline-hello-world/target/*
    - name: Testspace client install & config
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}
    - name: Testspace push test content
      run: testspace "[${{ github.workflow }}/${{ github.job}}]./testcontent/*.xml"
